feat: Join the community
InventorsDev/theinventors pull request #1
Opened 2022-11-03 17:45 UTC by Roxie-32

The API to join the community

2022-11-03 19:34 UTC, willypelz commented
@Roxie-32, please take a look at the comment on the PR.

2022-11-03 19:47 UTC, willypelz requested changes

2022-11-03 19:47 UTC, willypelz commented on inventorbackend/app/Http/Controllers/JoinUsController.php
> +                'msg' => 'Thank you for indicating your interest to join our community, We will get in touch shortly !'
can you try and abstract the response for all your API? so you will not have WET code

There are several ways you can abstract the code. 

you can use a class, here is a quick sample using trait. 

```
trait RespondsWithHttpStatus
{
    protected function success($message, $data = [], $status = 200)
    {
        return response([
            'success' => true,
            'data' => $data,
            'message' => $message,
        ], $status);
    }

    protected function failure($message, $status = 422)
    {
        return response([
            'success' => false,
            'message' => $message,
        ], $status);
    }
}
```

2022-11-03 19:47 UTC, willypelz commented on inventorbackend/app/Http/Controllers/JoinUsController.php
> +                'msg' => 'Thank you for indicating your interest to join our community, We will get in touch shortly !'
so you will not have to repeat them all over your code. @Roxie-32

2022-11-03 19:47 UTC, willypelz commented on inventorbackend/app/Http/Requests/JoinUsRequest.php
> +            'email' => 'required|email',
awesome, this is amazing using form request

2022-11-03 19:47 UTC, willypelz commented on inventorbackend/database/migrations/2022_11_03_121719_create_join_us_table.php
> +            $table->string('email');
we can have a duplicate email at the database level. we need to do some level of validation at the migration level. 

unless the business logic supports that.

2022-11-08 09:20 UTC, Roxie-32 commented
@willypelz kindly check if the response is better now, thanks !

2022-11-11 16:04 UTC, merged